### PR TITLE
add HUGO_BASE_URL

### PR DESCRIPTION
**Pull request by rdamen**
Added HUGO_BASE_URL so I can easily configure a staging site.

### CODE REVIEW

**Comment by handcraftedbits** [comment]
Shouldn't you be able to create two separate Hugo units with different NGINX_URL_PREFIX values instead?

**Comment by rdamen** [comment]
Without changing the base URL all generated links would be pointing to the production site.

**Comment by rdamen** [comment]
Perhaps it would be better to generate the base URL setting from first host in NGINX_UNIT_HOSTS combined with NGINX_URL_PREFIX or something like that but I kept it simple for now to solve my problem quickly.

**Comment by handcraftedbits** [comment]
I've fixed it to automatically combine NGINX_UNITS_HOSTS and NGINX_URL_PREFIX.  This of course means you can't use multiple hosts/wildcards in NGINX_UNIT_HOSTS.

Now you should be able to create two Hugo units with different NGINX_URL_PREFIX and HUGO_REPO_BRANCH values.  You'll also need to create two webhooks in Github, one for your master branch and one for the other branch.  Thanks for you contributions!

**Comment by handcraftedbits** [comment]
FYI this will be on Docker Hub shortly with tag v0.18.1

**Pull request merged**
